### PR TITLE
GPU problems

### PR DESCRIPTION
**Pull request by mmatteo-hub**
Version of the code properly working but with the _cuda_ drivers not inserted to perform simulations also for those who do not have NVIDIA GPU availability.

### CODE REVIEW

**Comment by JulioPlaced** [comment]
Probably adding a try/catch would be cleaner and work for both gpu/non-gpu modes, e.g.,
```
try:
    import numba as nb
    from numba import cuda
    cuda.select_device(0)
except ModuleNotFoundError:
    print("Import error: Numba module not found")
except Exception as e:
    print("GPU not found: " + format(e))
```
Confirmed this import sequence is working in laptop with Nvidia. Can you try if this works on your pc without gpu?

**Comment by mmatteo-hub** [comment]
Ok so I checked also for my PC and it works with the try/catch so I think it is solved.
I will close it so you can merge it.
You can find the files attached in the dedicated section already updated.

**Comment by JulioPlaced** [comment]
I commit the changes instead of merging the pull request  to avoid having "gpu=false" as default option.
Further improvement could set "gpu" param automatically based on the successful import of numba & the gpu selection.

**Comment by mmatteo-hub** [comment]
If you open I will change and then you can merge it.

**Pull request closed without merging**
